"""add_mentor_sessions_table

Revision ID: 01f44cb84f03
Revises: a5795540fa44
Create Date: 2026-06-24 21:43:39.952584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f44cb84f03'
down_revision: Union[str, Sequence[str], None] = 'a5795540fa44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('source_ids', sa.Text(), nullable=True),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('gap_report', sa.Text(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mentor_sessions_status', 'mentor_sessions', ['status'], unique=False)
    op.create_index('ix_mentor_sessions_topic', 'mentor_sessions', ['topic'], unique=False)
    op.create_index(op.f('ix_mentor_sessions_user_id'), 'mentor_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_mentor_sessions_workspace_id'), 'mentor_sessions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentor_sessions_workspace_id'), table_name='mentor_sessions')
    op.drop_index(op.f('ix_mentor_sessions_user_id'), table_name='mentor_sessions')
    op.drop_index('ix_mentor_sessions_topic', table_name='mentor_sessions')
    op.drop_index('ix_mentor_sessions_status', table_name='mentor_sessions')
    op.drop_table('mentor_sessions')
    # ### end Alembic commands ###
