"""add model/temperature to chat_sessions

Revision ID: 12225ad9fa3d
Revises: e251248d244c
Create Date: 2026-06-21 18:57:41.134622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12225ad9fa3d'
down_revision: Union[str, Sequence[str], None] = 'e251248d244c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('model', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'temperature')
    op.drop_column('chat_sessions', 'model')
    # ### end Alembic commands ###
