"""add_learning_path_tables

Revision ID: a5795540fa44
Revises: 87e0037f166b
Create Date: 2026-06-24 21:06:39.847765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5795540fa44'
down_revision: Union[str, Sequence[str], None] = '87e0037f166b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_topics', sa.Integer(), nullable=True),
    sa.Column('completed_topics', sa.Integer(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_paths_status', 'learning_paths', ['status'], unique=False)
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_workspace_id'), 'learning_paths', ['workspace_id'], unique=False)
    op.create_table('learning_path_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learning_path_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('source_ids', sa.Text(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_topics_learning_path_id'), 'learning_path_topics', ['learning_path_id'], unique=False)
    op.create_index('ix_lp_topic_sort_order', 'learning_path_topics', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lp_topic_sort_order', table_name='learning_path_topics')
    op.drop_index(op.f('ix_learning_path_topics_learning_path_id'), table_name='learning_path_topics')
    op.drop_table('learning_path_topics')
    op.drop_index(op.f('ix_learning_paths_workspace_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index('ix_learning_paths_status', table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
