import axios from 'axios';
import { retry } from '../utils/retry';
import { config } from '../config';

const YOUTUBE_API_BASE = 'https://www.googleapis.com/youtube/v3';

export interface VideoMetadata {
  title: string;
  channelName: string;
  duration: string;
  thumbnailUrl: string;
}

export interface TranscriptResult {
  text: string;
  language: string;
  isAutoGenerated: boolean;
}

/**
 * Fetches video metadata (title, channel, duration, thumbnail) from YouTube Data API v3.
 */
export async function fetchVideoMetadata(videoId: string): Promise<VideoMetadata> {
  try {
    return await retry(async () => {
      const response = await axios.get(`${YOUTUBE_API_BASE}/videos`, {
        params: {
          key: config.googleApiKey,
          id: videoId,
          part: 'snippet,contentDetails',
        },
      });

      const items = response.data.items;
      if (!items || items.length === 0) {
        throw new Error(`Video not found: ${videoId}`);
      }

      const item = items[0];
      const snippet = item.snippet;
      const contentDetails = item.contentDetails;

      return {
        title: snippet.title,
        channelName: snippet.channelTitle,
        duration: formatDuration(contentDetails.duration),
        thumbnailUrl:
          snippet.thumbnails?.maxres?.url ||
          snippet.thumbnails?.high?.url ||
          snippet.thumbnails?.medium?.url ||
          `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
      };
    });
  } catch (err) {
    console.warn(`Data API failed for metadata (${videoId}), trying fallback...`);
    try {
      const response = await axios.get(`https://www.youtube.com/watch?v=${videoId}`, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
          'Accept-Language': 'en-US,en;q=0.9',
        }
      });
      const html = response.data as string;
      
      const titleMatch = html.match(/<title>(.*?)<\/title>/);
      let title = titleMatch ? titleMatch[1].replace(' - YouTube', '') : 'Unknown Video';
      
      // Try to extract channel name
      const channelMatch = html.match(/"ownerChannelName":"([^"]+)"/);
      const channelName = channelMatch ? channelMatch[1] : 'Unknown Channel';
      
      // Try to extract duration
      const lengthMatch = html.match(/"lengthSeconds":"(\d+)"/);
      let duration = '0:00';
      if (lengthMatch) {
        const seconds = parseInt(lengthMatch[1], 10);
        const h = Math.floor(seconds / 3600);
        const m = Math.floor((seconds % 3600) / 60);
        const s = seconds % 60;
        if (h > 0) {
          duration = `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
        } else {
          duration = `${m}:${String(s).padStart(2, '0')}`;
        }
      }
      
      return {
        title,
        channelName,
        duration,
        thumbnailUrl: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
      };
    } catch (fallbackErr) {
      console.error('Fallback metadata fetch failed:', (fallbackErr as Error).message);
      // Return bare minimum metadata rather than throwing
      return {
        title: 'Unknown Video',
        channelName: 'Unknown Channel',
        duration: '0:00',
        thumbnailUrl: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
      };
    }
  }
}

/**
 * Converts ISO 8601 duration (PT1H2M30S) to human-readable format (1:02:30).
 */
function formatDuration(isoDuration: string): string {
  const match = isoDuration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return '0:00';

  const hours = parseInt(match[1] || '0', 10);
  const minutes = parseInt(match[2] || '0', 10);
  const seconds = parseInt(match[3] || '0', 10);

  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
  }
  return `${minutes}:${String(seconds).padStart(2, '0')}`;
}

/**
 * Primary method: Fetches transcript via YouTube Data API v3 captions.list + captions.download.
 * Note: captions.download requires OAuth in some cases; we attempt it and fall back gracefully.
 */
async function fetchTranscriptViaDataApi(videoId: string): Promise<TranscriptResult | null> {
  try {
    // List available caption tracks
    const listResponse = await retry(() =>
      axios.get(`${YOUTUBE_API_BASE}/captions`, {
        params: {
          key: config.googleApiKey,
          videoId,
          part: 'snippet',
        },
      })
    );

    const captions = listResponse.data.items || [];
    if (captions.length === 0) return null;

    // Prefer manual captions over auto-generated, prefer English
    const sorted = [...captions].sort((a: any, b: any) => {
      const aManual = a.snippet.trackKind === 'standard' ? 0 : 1;
      const bManual = b.snippet.trackKind === 'standard' ? 0 : 1;
      const aEn = a.snippet.language?.startsWith('en') ? 0 : 1;
      const bEn = b.snippet.language?.startsWith('en') ? 0 : 1;
      return aManual - bManual || aEn - bEn;
    });

    const track = sorted[0];
    const isAutoGenerated = track.snippet.trackKind !== 'standard';

    // captions.download requires OAuth for most videos — this typically returns 403
    // We try anyway, then fall back in the caller
    const downloadResponse = await retry(() =>
      axios.get(`${YOUTUBE_API_BASE}/captions/${track.id}`, {
        params: {
          key: config.googleApiKey,
          tfmt: 'vtt',
        },
        responseType: 'text',
      })
    );

    const text = parseVtt(downloadResponse.data);
    if (text.split(/\s+/).length < 30) return null;

    return { text, language: track.snippet.language, isAutoGenerated };
  } catch {
    return null;
  }
}

/**
 * Fallback method: Fetches transcript via timedtext endpoint (unofficial but reliable).
 */
async function fetchTranscriptViaTimedtext(videoId: string): Promise<TranscriptResult | null> {
  const baseHeaders = {
    'User-Agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept-Language': 'en-US,en;q=0.9',
    'Accept': '*/*',
  };

  // First, try to list available caption tracks
  let availableLangs: string[] = [];
  try {
    const listUrl = `https://www.youtube.com/api/timedtext?v=${videoId}&type=list`;
    const listResp = await axios.get(listUrl, {
      headers: baseHeaders,
      timeout: 10000,
    });

    if (listResp.data && typeof listResp.data === 'string') {
      // Parse XML list to find available tracks
      const langMatches = listResp.data.match(/lang_code="([^"]+)"/g) || [];
      availableLangs = langMatches.map((m) => m.replace(/lang_code="|"/g, ''));
      console.log(`Available caption languages for ${videoId}:`, availableLangs);
    }
  } catch (err) {
    console.log(`Failed to list captions for ${videoId}:`, (err as Error).message);
  }

  // Try common language candidates first
  const langCandidates = ['en', 'en-US', 'en-GB'];

  for (const lang of langCandidates) {
    try {
      // Try both regular and auto-generated captions
      const urls = [
        `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${lang}&fmt=vtt`,
        `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${lang}&asr=1&fmt=vtt`,
      ];

      for (const url of urls) {
        const response = await axios.get(url, {
          headers: baseHeaders,
          timeout: 10000,
        });

        if (response.data && typeof response.data === 'string' && response.data.length > 50) {
          const text = parseVtt(response.data);
          if (text.split(/\s+/).length >= 30) {
            console.log(`✅ Found captions via timedtext (${lang}) for ${videoId}`);
            return {
              text,
              language: lang,
              isAutoGenerated: url.includes('asr=1'),
            };
          }
        }
      }
    } catch {
      // Try next language
    }
  }

  // Try available languages from the list
  for (const lang of availableLangs) {
    try {
      const url = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${lang}&fmt=vtt`;
      const response = await axios.get(url, {
        headers: baseHeaders,
        timeout: 10000,
      });

      if (response.data && typeof response.data === 'string' && response.data.length > 50) {
        const text = parseVtt(response.data);
        if (text.split(/\s+/).length >= 30) {
          console.log(`✅ Found captions via timedtext (${lang}) for ${videoId}`);
          return {
            text,
            language: lang,
            isAutoGenerated: true,
          };
        }
      }
    } catch {
      // continue
    }
  }

  return null;
}

/**
 * Parses a VTT caption file into clean plain text.
 */
function parseVtt(vttContent: string): string {
  // Remove WEBVTT header and metadata blocks
  const lines = vttContent.split('\n');
  const textLines: string[] = [];
  let lastLine = '';

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip WEBVTT header, timestamps, and cue IDs
    if (
      trimmed === 'WEBVTT' ||
      trimmed.startsWith('NOTE') ||
      trimmed.startsWith('STYLE') ||
      trimmed.match(/^\d{2}:\d{2}:\d{2}/) ||
      trimmed.match(/^\d{2}:\d{2}[\.,]/) ||
      trimmed.match(/^-->/)
    ) {
      continue;
    }

    // Skip pure numeric cue IDs
    if (/^\d+$/.test(trimmed)) continue;

    if (trimmed && trimmed !== lastLine) {
      // Remove HTML tags (like <c>, <b>, italic markers)
      const cleaned = trimmed.replace(/<[^>]+>/g, '').trim();
      if (cleaned) {
        textLines.push(cleaned);
        lastLine = trimmed;
      }
    }
  }

  return cleanTranscriptText(textLines.join(' '));
}

/**
 * Parses SRT format captions to plain text.
 */
export function parseSrt(srtContent: string): string {
  const lines = srtContent.split('\n');
  const textLines: string[] = [];
  let lastLine = '';

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (/^\d+$/.test(trimmed)) continue;
    if (trimmed.match(/^\d{2}:\d{2}:\d{2}[,\.]/)) continue;

    if (trimmed !== lastLine) {
      textLines.push(trimmed);
      lastLine = trimmed;
    }
  }

  return cleanTranscriptText(textLines.join(' '));
}

/**
 * Cleans and normalises transcript text.
 */
function cleanTranscriptText(text: string): string {
  return text
    // Remove speaker labels and sound effects in brackets
    .replace(/\[([^\]]+)\]/g, '')
    // Remove HTML entities
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    // Normalise whitespace
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Main transcript fetch function. Tries Data API first, falls back to timedtext.
 */
export async function fetchTranscript(videoId: string): Promise<TranscriptResult> {
  console.log(`Fetching transcript for video: ${videoId}`);

  // Try Data API first
  const dataApiResult = await fetchTranscriptViaDataApi(videoId);
  if (dataApiResult) {
    console.log(`✅ Transcript fetched via Data API for ${videoId}`);
    return dataApiResult;
  }

  console.log(`Data API failed for ${videoId}, trying timedtext fallback...`);

  // Fall back to timedtext
  const timedtextResult = await fetchTranscriptViaTimedtext(videoId);
  if (timedtextResult) {
    console.log(`✅ Transcript fetched via timedtext for ${videoId}`);
    return timedtextResult;
  }

  console.log(`❌ No captions found for ${videoId}`);
  throw Object.assign(new Error('No captions available for this video.'), {
    code: 'NO_CAPTIONS',
  });
}
